### PR TITLE
fix(testing): remove jasmine dependency

### PR DESCRIPTION
**Pull request by MillerSvt**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Build or CI related changes
- [x] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Schematic tests are running separately via jasmine

## What is the new behaviour?

Schematic tests are running together with cdk tests via jest. Jasmine dependency dropped.

### CODE REVIEW

**Comment by vladimirpotekhin** [comment]
seems like something wrong with schematic tests
Снимок экрана 2023-11-24 в 10 45 28
Снимок экрана 2023-11-24 в 10 45 46

**Comment by MillerSvt** [comment]
> seems like something wrong with schematic tests

Try `nx run cdk:test --skip-nx-cache` please

**Comment by splincode** [comment]
@MillerSvt can we add these spec patterns files to Nx cache recalculations?

**Comment by MillerSvt** [comment]
@vladimirpotekhin @splincode This happens not only for schematic tests, but also for all cdk tests at least. I think you should make a separate task for this.

image
image

**Comment by vladimirpotekhin** [comment]
> > seems like something wrong with schematic tests
> 
> @vladimirpotekhin Try `nx run cdk:test --skip-nx-cache` please. It works for me: image image

Indeed, the problem is in the nx cache.
Thank you!

**Review by vladimirpotekhin — APPROVED** [review]

**Pull request merged**
