### PR TITLE
fix(core): `.t-cell` right interval update

### LINKED ISSUE #8444: 🐞 - calendar does not display cells correctly
### Playground Link

v4.x

### Description

image

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### PR DESCRIPTION
**Pull request by mdlufy**
Close #8444

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Comment by splincode** [comment]
image

**Comment by mdlufy** [comment]
> image

It's bad (

**Comment by mdlufy** [comment]
> image

For some reason, there are no changes on the https://taiga-previews--pr8753-mdlufy-calendar-cell-0ul7mdze.web.app/components/calendar-range, although the styles have changed 
image

**Comment by hakimio** [comment]
@mdlufy 
Maybe it was needed to update both `scss` and `less` files?

**Pull request closed without merging**
