### PR TITLE
fix(core): fix dropdown-context directive on touchscreen laptops

### PR DESCRIPTION
**Pull request by MillerSvt**
Closes #

### CODE REVIEW

**Review by splincode — APPROVED** [review]

**Review by waterplea — APPROVED** [review]

**Comment by splincode** [comment]
@MillerSvt could you rebase please

**Comment by MillerSvt** [comment]
@splincode its actual

**Comment by splincode** [comment]
@MillerSvt can you trigger CI pipeline? by empty commit

image

**Comment by splincode** [comment]
@MillerSvt build failed

**Pull request merged**
