### PR TITLE
chore(demo): improve icons demonstration

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

### CODE REVIEW

**Review by waterplea — COMMENTED** [review]
Looks good, let's just not remove them when they go out of the viewport.

**Comment by splincode** [comment]
`let's just not remove them when they go out of the viewport.`

what do you mean?(

**Comment by waterplea** [comment]
> `let's just not remove them when they go out of the viewport.`
> 
> what do you mean?(

I mean only set them to `true` once they intersect and keep them `true`, do not switch to `false` when it goes away from the viewport.

**Comment by splincode** [comment]
`do not switch to false when it goes away from the viewport.` 
Due to the large number of DOM elements, the page begins to slow down

I tested it in the proprietary version

**Review by waterplea — APPROVED** [review]

**Review by vladimirpotekhin — APPROVED** [review]

**Pull request merged**
