### PR TITLE
ci: enable `functional/no-loop-statements`

### PR DESCRIPTION
**Pull request by splincode**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

### CODE REVIEW

**Comment by vladimirpotekhin** [comment]
There seems to be too much "//eslint-disable-next-line function/no-loop-statements"
Maybe it's better not to add this rule?

**Comment by waterplea** [comment]
What do you think, @vladimirpotekhin @nsbarsukov , should this be a rule?

**Comment by splincode** [comment]
@vladimirpotekhin 
I can enable only for `for-of` for remove `//eslint-disable-next-line function/no-loop-statements`

**Comment by nsbarsukov** [comment]
> What do you think, @vladimirpotekhin @nsbarsukov , should this be a rule?

I think that is OK for `for ... of` => `forEach` only

**Comment by splincode** [comment]
@waterplea @vladimirpotekhin @nsbarsukov updated

**Pull request closed without merging**
