### PR TITLE
chore: support rel property for links

### PR DESCRIPTION
**Pull request by splincode**
Closes #

### CODE REVIEW

**Comment by waterplea** [comment]
Haven't I commented on this one somewhere already? I think it's excessive, can we just add `rel="noopener noreferrer"`?

**Comment by splincode** [comment]
@waterplea updated

**Review by waterplea — APPROVED** [review]
Let's make it `chore`

**Comment by splincode** [comment]
@vladimirpotekhin please review

**Review by vladimirpotekhin — APPROVED** [review]

**Pull request merged**
