### PR TITLE
chore(demo): improve LCP

### PR DESCRIPTION
**Pull request by splincode**

### CODE REVIEW

**Comment by waterplea** [comment]
Looks excessive

**Comment by splincode** [comment]
@waterplea without inline image on SSR

image

**Comment by waterplea** [comment]
> @waterplea without inline images on SSR
> 
> image
> 

But why is that? 🤔 Is it generating broken links?

**Comment by splincode** [comment]
@waterplea SSR just gives out static

and we can inline images so that additional requests are not sent, and the picture is displayed immediately

**Pull request closed without merging**
