### PR TITLE
ci: support import/no-cycle

### LINKED ISSUE #2750: 🤖 - `eslint-plugin` add `no-import-circular-deps`
## Problem

**projects/testing/core/badge.harness.ts:**
```ts
import {TuiComponentHarness} from '@taiga-ui/testing';
```
It breaks build because it produces circular dependency:
```console
Entry point @taiga-ui/testing has a circular dependency on @taiga-ui/testing/core.
```
To fix build it should be corrected to:
```ts
import {TuiComponentHarness} from '@taiga-ui/testing/utils';
```

## Proposed solution
Write eslint-rule (with autofix!).

### PR DESCRIPTION
**Pull request by ddubrava**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactoring
- [x] Code style update
- [ ] Build or CI related changes
- [ ] Documentation content changes

## What is the current behavior?

Closes #2750

## What is the new behavior?

`import/no-cycle` is added

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by splincode** [comment]
@nsbarsukov @ddubrava 

image

**Comment by ddubrava** [comment]
ye, I've seen all these errors. I'm not sure I can fix them properly, architecture stuff.
I can give it a try.

**Comment by waterplea** [comment]
Seems like they could be fixed by `import type`, can they? At least some of them.

**Comment by ddubrava** [comment]
Hi! I fixed some errors but not all. There are a lot of issues with importing components, directives, constants etc.

**Comment by splincode** [comment]
@waterplea I think we will not get profit, maybe we should close this PR

**Comment by ddubrava** [comment]
If it's possible it's better to avoid circular dependencies. They lead to problems in most cases, e.g. domino effect and so on

**Comment by ddubrava** [comment]
> @ddubrava can we fix this situation?
> 
> line-chart.component.ts -> line-chart-hint.directive.ts -> line-chart.component.ts
> 
> https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-charts/components/line-chart/line-chart.component.ts#L35 https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-charts/components/line-chart/line-chart-hint.directive.ts#L28

Ye, I'm not sure about the correct approach but you can inject the directive by an injection token. And the injection token is stored in the another file. I think it will fix the issue but I'm not sure that it can improve sth. And it's probably just a hack, I mean It fixes the issue but fixes it in the wrong way.

And I think it might be ok to have circular dependencies if you have two entities that are strongly connected. I mean you can't use this hint without the component and vice versa.

**Comment by splincode** [comment]
I think we can close this PR and investigate [this](https://github.com/Tinkoff/taiga-ui/pull/2865/files) one in the future

**Pull request closed without merging**
