### PR TITLE
fix(core): do not override passed empty id

### PR DESCRIPTION
**Pull request by splincode**
In my tests I wanna use empty id, but now it doesn't work as expected

```html
<input id="" />
```

### CODE REVIEW

**Comment by waterplea** [comment]
That wouldn't work because if you omit `id` completely it's empty string, not `null` or `undefined`.

**Comment by splincode** [comment]
`That wouldn't work because if you omit id completely it's empty string, not null or undefined.`

ha, that's what I needed

**Comment by waterplea** [comment]
We use auto id because we need input to be linked with label even when no id is provided.

**Comment by splincode** [comment]
`be linked with label even when no id is provided.` hm, okey

**Pull request closed without merging**
